/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClosRouteImport } from './routes/clos'
import { Route as CognitiveOsRouteImport } from './routes/cognitive-os'
import { Route as RoutingRouteImport } from './routes/routing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosRoute = ClosRouteImport.update({
  id: '/clos',
  path: '/clos',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveOsRoute = CognitiveOsRouteImport.update({
  id: '/cognitive-os',
  path: '/cognitive-os',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clos': typeof ClosRoute
  '/cognitive-os': typeof CognitiveOsRoute
  '/routing': typeof RoutingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clos': typeof ClosRoute
  '/cognitive-os': typeof CognitiveOsRoute
  '/routing': typeof RoutingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clos': typeof ClosRoute
  '/cognitive-os': typeof CognitiveOsRoute
  '/routing': typeof RoutingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clos' | '/cognitive-os' | '/routing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clos' | '/cognitive-os' | '/routing'
  id: '__root__' | '/' | '/clos' | '/cognitive-os' | '/routing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosRoute: typeof ClosRoute
  CognitiveOsRoute: typeof CognitiveOsRoute
  RoutingRoute: typeof RoutingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clos': {
      id: '/clos'
      path: '/clos'
      fullPath: '/clos'
      preLoaderRoute: typeof ClosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-os': {
      id: '/cognitive-os'
      path: '/cognitive-os'
      fullPath: '/cognitive-os'
      preLoaderRoute: typeof CognitiveOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosRoute: ClosRoute,
  CognitiveOsRoute: CognitiveOsRoute,
  RoutingRoute: RoutingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
